import { groq } from "next-sanity";
import { client } from '../../../lib/sanity.client'

import Navbar from '../../components/Navbar';
import Frame from '../../components/Frame';
import "../../styles/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

async function RootLayout({ children }) {
  const authorQuery = groq`*[_type=='author'][0].name`;
  const author = await client.fetch(authorQuery);

  return (
    <html lang="en">
      <body>
        <div className="relative h-screen font-thin">
          <Frame />
          <div className="absolute flex flex-col w-[94.5vw] h-[93.5vh] m-auto left-0 right-0 top-0 bottom-0 z-[2] sm:flex-row sm:p-9">
            <Navbar author={author} />
            <div className="h-40 w-full sm:hidden"></div>
            <div className="flex h-full w-full px-5 pb-5 sm:p-0">
              {children}
            </div>
          </div>
        </div>
        <div className="z-[1]">
          <video
            autoPlay
            className="absolute border border-[#F1DAC4] object-cover w-[95vw] h-[94vh] m-auto left-0 right-0 top-0 bottom-0 z-0"
            loop
            muted
          >
            <source src="/backgroundVideo.mp4" type="video/mp4" />
          </video>
        </div>
      </body>
    </html>
  )
}

export default RootLayout;
