
import { groq } from "next-sanity";
import { client } from '../../../lib/sanity.client'

import Background from '../../components/Background';
import Navbar from '../../components/Navbar';
import Frame from '../../components/Frame';
import Page from '../../components/Page';
import "../../styles/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

async function RootLayout({ children }) {
  const authorQuery = groq`*[_type=='author'][0].name`;
  const author = await client.fetch(authorQuery);

  return (
    <html lang="en">
      <body>
        <div className="relative h-screen font-thin">
          <Frame />
          <Page author={author}>
            {children}
          </Page>
        </div>
      </body>
    </html>
  )
}

export default RootLayout;
