"use client"
import Navbar from '../../components/Navbar';
import Frame from '../../components/Frame';
import "../../styles/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="relative h-screen">
          <Frame />
          <div className="absolute flex w-[94.5vw] h-[93.5vh] m-auto left-0 right-0 top-0 bottom-0 z-[1] p-9">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}

export default RootLayout;
